/**
 * CHUNHUI_WEB — English content (SITE_DATA_EN)
 * Loaded alongside data.js; i18n.js swaps window.SITE_DATA when lang='en'.
 */

const SITE_DATA_EN = {

  company: {
    name: "Zhongshan Chunhui Door Industry Co., Ltd.",
    displayName: "Chunhui Door Industry",
    nameEn: "CHUNHUI DOOR",
    slogan: "Chunhui Doors",
    sloganSub: "Manufacturer of Solid Wood Lacquered, Aluminum-Wood, Engineering & Custom Interior Doors",
    founded: "2012",
    phone: "0760-8820 3678",
    mobile: "13809689692",
    email: "7477461@qq.com",
    secondaryEmail: "Dengsan568@gmail.com",
    address: "No.7 Longtang Industrial Ave, Wuguishan Town, Zhongshan, Guangdong, China",
    branchAddress: "Hengmei Garden Shanzai Industrial Zone, Nanqu, Zhongshan, Guangdong",
    contactPerson: "Mr. Situ",
    wechat: "chunhui_door",
    icp: "粤ICP备2025498719号-1",
  },

  stats: [
    { number: "2012", label: "Founded" },
    { number: "500+", label: "Partner Stores" },
    { number: "188", label: "Product Models" },
    { number: "Bulk", label: "Hotel / Apt Projects" },
  ],

  solutions: [
    {
      audience: "Home Renovation",
      title: "Choose the right interior door by space and budget",
      desc: "For new homes, renovations, and full-house customization. Focus on aesthetics, eco-friendliness, durability, and overall home décor coordination.",
      points: ["Solid Wood Lacquered", "Aluminum-Wood", "Engineering Doors", "Custom Doors"],
      cta: "Get Home Décor Advice",
    },
    {
      audience: "Engineering Clients",
      title: "Stable door supply for hotels, apartments & premium projects",
      desc: "For bulk supply, uniform styles, phased delivery, and project schedule management. Focus on lead time, quality consistency, and after-sales response.",
      points: ["Engineering Doors", "Bulk Supply", "Project Support", "Delivery Schedule"],
      cta: "Inquire Engineering Supply",
    },
    {
      audience: "Distributors / Decorators",
      title: "Rich product range with long-term channel cooperation",
      desc: "For regional distributors, designer channels, and interior design companies. Focus on product series, sample support, and stable long-term supply.",
      points: ["Product Catalog", "Sample Support", "Channel Partnership", "Long-term Supply"],
      cta: "Learn About Partnership",
    },
  ],

  productCategories: ["All", "Solid Wood Lacquered", "Aluminum-Wood"],

  products: [
    {
      id: 1,
      name: "Oak Deep-Carved Series · CHA-97",
      series: "Solid Wood Lacquered",
      desc: "Imported oak, deep carving craftsmanship, strong three-dimensional effect, showcasing premium taste",
      tag: "Artisan Craft",
      price: "Custom Quote",
      image: "chanpinzhanshi/kaoqimen/shimukaoqimen/xiangmumen/橡木深雕门系列CHA-97_1.jpg",
      accent: "#5C4A2A",
    },
    {
      id: 2,
      name: "M9 Series Aluminum-Wood Door",
      series: "Aluminum-Wood",
      desc: "Healthy paint-free door, moisture-resistant and warp-proof, M9 green health board, uniform integrated design",
      tag: "Eco & Healthy",
      price: "Custom Quote",
      image: "chanpinzhanshi/wuqimen/lvmumen/M9系列 同色铝木门·健康无漆木门（防潮抗变 - M9绿色健康板）_1.png",
      accent: "#2A5C3A",
    },
    {
      id: 3,
      name: "Flat-Carved Series · CHA-24",
      series: "Solid Wood Lacquered",
      desc: "Classic flat-carved design, clean flowing lines, versatile for any home décor style",
      tag: "Classic",
      price: "Custom Quote",
      image: "chanpinzhanshi/kaoqimen/shimukaoqimen/pingdiaomen/平雕门系列CHA-24_1.jpg",
      accent: "#7A3A1A",
    },
    {
      id: 4,
      name: "Glass Door Series · CHA-B01",
      series: "Solid Wood Lacquered",
      desc: "Transparent glass design, balancing light and partition, ideal for study rooms and kitchens",
      tag: "Light & Airy",
      price: "Custom Quote",
      image: "chanpinzhanshi/kaoqimen/shimukaoqimen/bolimen/玻璃门系列CHA-B01_1.jpg",
      accent: "#3A5C8B",
    },
    {
      id: 5,
      name: "Wood Veneer Craft Series · CHA-146",
      series: "Solid Wood Lacquered",
      desc: "Natural wood veneer finish, exquisite craftsmanship, natural grain, enhancing spatial quality",
      tag: "Natural Texture",
      price: "Custom Quote",
      image: "chanpinzhanshi/kaoqimen/shimukaoqimen/mupigongyimen/木皮工艺门系列CHA-146_1.jpg",
      accent: "#6B4226",
    },
    {
      id: 6,
      name: "Fashion White Door Series · CHA-176",
      series: "Solid Wood Lacquered",
      desc: "Pure white minimalist design, clean and versatile, ideal for modern and Nordic home décor",
      tag: "Minimal Match",
      price: "Custom Quote",
      image: "chanpinzhanshi/kaoqimen/shimukaoqimen/shishangbaimen/时尚白门系列CHA-176_1.jpg",
      accent: "#8A8A8A",
    },
  ],

  allProducts: SITE_DATA.allProducts,

  process: [
    { step: "01", title: "Requirements Discussion", desc: "Confirm customer type, product series, space scenario, quantity, budget, and delivery city." },
    { step: "02", title: "Product Recommendation", desc: "Based on home, engineering, hotel, apartment, or distribution needs, recommend door types and surface finishes." },
    { step: "03", title: "Quotation", desc: "Form initial quote reference based on materials, dimensions, quantity, hardware, and delivery schedule." },
    { step: "04", title: "Production Schedule", desc: "After confirming order details, enter production and QC process to ensure stable bulk delivery." },
    { step: "05", title: "Shipping & After-Sales", desc: "Ship according to project milestones, providing follow-up installation, replacement, and maintenance support." },
  ],

  about: {
    title: "Founded in 2012, Dedicated to Stable Door Delivery",
    lead: "Zhongshan Chunhui Door Industry Co., Ltd. is located in Zhongshan, Guangdong, specializing in solid wood lacquered doors, aluminum-wood doors, engineering doors, and custom interior doors.",
    content: "We serve home clients, hotel/apartment engineering projects, distributors, and interior design companies, focusing on product selection, customization, bulk supply, delivery coordination, and after-sales support.",
    image: "ziyuan/images/banner_01.jpg",
    serviceScope: ["Solid Wood Lacquered", "Aluminum-Wood", "Engineering Doors", "Custom Doors"],
    targetClients: ["Home Clients", "Engineering Clients", "Hotels & Apts", "Distributors", "Design Companies"],
    quickFacts: [
      { value: "2012", label: "Founded", desc: "Long-term focus on interior door manufacturing" },
      { value: "500+", label: "Partner Stores", desc: "Supporting regional channels and distributor partnerships" },
      { value: "188", label: "Product Models", desc: "Covering multi-style, multi-scenario selection" },
    ],
    highlights: [
      { icon: "01", title: "Rich Product Range", desc: "From home interior doors to engineering doors, covering different budgets, styles, and usage scenarios" },
      { icon: "02", title: "Stable Factory Delivery", desc: "Established standard processes for materials, craftsmanship, QC, scheduling, and bulk supply" },
      { icon: "03", title: "Engineering-Friendly", desc: "Suitable for hotels, apartments, premium projects requiring uniform styles and phased delivery" },
      { icon: "04", title: "Direct Channel Cooperation", desc: "Supports distributors and design companies in communicating samples, catalogs, supply cycles, and after-sales" },
    ],
    proofTitle: "Service Support from Selection to After-Sales",
    proofPoints: [
      "Recommend products based on space, budget, and project needs",
      "Coordinate production and delivery for bulk projects",
      "Provide follow-up restocking and after-sales support",
    ],
    ctaText: "Submit Requirements, Get Product Suggestions",
    ctaHref: "lianxiwomen/index.html",
    timeline: [
      { year: "2012", event: "Chunhui Doors founded, first production line launched" },
      { year: "2014", event: "Introduced advanced equipment from Italy and Germany" },
      { year: "2018", event: "Launched Guochao Moying series, warmly received by market" },
      { year: "2024", event: "Nationwide partner stores exceeded 500, products exported overseas" },
    ],
    scope: [
      { title: "Solid Wood Lacquered", desc: "For spaces that value texture, craftsmanship, and premium home atmosphere. Includes 5 sub-series: Carved, Oak, Glass, Wood Veneer, and Fashion White." },
      { title: "Aluminum-Wood Doors", desc: "Balances structural stability, paint-free health benefits, and modern aesthetic." },
      { title: "Engineering Doors", desc: "For hotels, apartments, and premium projects. Uniform specs and reliable delivery rhythm." },
      { title: "Custom Interior Doors", desc: "Customized dimensions, colors, and hardware based on space, budget, and project needs." },
    ],
    clients: [
      { title: "Home Clients", desc: "Selection advice balancing aesthetics, eco-friendliness, budget, space coordination, and durability." },
      { title: "Engineering Clients", desc: "Supports quantity, specifications, lead time, QC, and phased delivery." },
      { title: "Hotels & Apartments", desc: "Supports uniform style, project milestones, follow-up restocking, and after-sales response." },
      { title: "Distributors", desc: "Provides samples, catalogs, product series, and stable long-term supply support." },
      { title: "Design Companies", desc: "Assists with solution consultation, project selection, and door product configuration." },
    ],
    answers: [
      { q: "What types of doors does Chunhui produce?", a: "Chunhui produces solid wood lacquered doors, aluminum-wood doors, engineering doors, and custom interior doors — covering home, engineering, hotels, distributors, and design companies." },
      { q: "Can engineering projects have bulk supply?", a: "Yes. Engineering clients can provide project type, quantity, delivery city, style, and budget range. Chunhui will give initial recommendations based on product series, process configuration, and delivery milestones." },
      { q: "Is partnership suitable for distributors or design companies?", a: "Yes. Chunhui can discuss long-term cooperation around product systems, samples, catalogs, supply cycles, and after-sales, helping channel clients form clearer sales solutions." },
    ],
    trustStrip: {
      founded: { label: "Founded", desc: "Long-term focus on interior door manufacturing" },
      location: { value: "Zhongshan", label: "Manufacturing Base", desc: "Serving South China and national partner clients" },
    },
  },

  news: [
    {
      id: 1,
      date: "2025-05-18",
      category: "Care Tips",
      title: "Chunhui Doors | Door Maintenance Details You Should Know",
      summary: "Chunhui Doors teaches door maintenance: four don'ts for cleaning, five recommendations, and daily care tips. Regular maintenance preserves gloss and extends the life of your wooden doors.",
      image: "xinwendongtai/news_01.jpg",
    },
    {
      id: 2,
      date: "2025-04-22",
      category: "Brand News",
      title: "Chunhui Doors | Why Choosing the Right Door Matters",
      summary: "Wooden doors are essential durables for every home — material quality matters most. Chunhui uses imported wood tested against national standards to create high-quality home spaces.",
      image: "xinwendongtai/news_02.jpg",
    },
    {
      id: 3,
      date: "2025-03-15",
      category: "Brand News",
      title: "Chunhui Doors | Simplify to Perfection, Savor a Beautiful Life",
      summary: "Less is more luxurious. Simple but not simplistic — an ideal home with style, quality, and artistic spirit. In this space where light and life merge, excellence speaks for itself.",
      image: "xinwendongtai/news_03.jpg",
    },
  ],

  newsCategories: ["All", "Brand News", "Product Knowledge", "Buying Guide", "Engineering Cases"],

  caseStudies: [
    {
      id: 1,
      title: "Hotel & Apartment Engineering Door Supply",
      type: "Engineering Case",
      scene: "Hotel / Apartment",
      desc: "For bulk projects, focusing on uniform styles, delivery rhythm, durability, and replacement response.",
      image: "ziyuan/images/banner_03.jpg",
      tags: ["Engineering Doors", "Bulk Supply", "Stable Delivery"],
    },
    {
      id: 2,
      title: "Full-House Custom Interior Door for Home Décor",
      type: "Home Décor Case",
      scene: "Residential / Premium",
      desc: "Based on space style, budget, and family usage habits, recommending solid wood lacquered or aluminum-wood door series.",
      image: "ziyuan/images/banner_01.jpg",
      tags: ["Custom Doors", "Solid Wood Lacquered", "Home Décor"],
    },
    {
      id: 3,
      title: "Distributor Store Product Display System",
      type: "Channel Case",
      scene: "Distribution / Design",
      desc: "Provides product catalogs, sample displays, and key series support to help stores conduct product introductions and client consultations.",
      image: "chanpinzhanshi/wuqimen/lvmumen/M9系列 同色铝木门·健康无漆木门（防潮抗变 - M9绿色健康板）_1.png",
      tags: ["Distribution", "Sample Support", "Product System"],
    },
  ],

  contentTopics: [
    { title: "What scenarios are Carbon Crystal Doors for?", desc: "Learn about carbon crystal door applications in wear resistance, easy cleaning, engineering supply, and home spaces." },
    { title: "How to choose between Solid Wood Lacquered and Aluminum-Wood?", desc: "Compare from material, surface finish, budget, and style compatibility perspectives." },
    { title: "What to note when bulk purchasing engineering doors?", desc: "Learn key procurement points: quantity, dimensions, lead time, installation, replacement, and after-sales." },
    { title: "What information do I need for custom interior doors?", desc: "Guide to preparing floor plan, dimensions, style, budget, quantity, and delivery city." },
  ],

  faqs: [
    {
      question: "What types of doors does Chunhui produce?",
      answer: "Chunhui covers solid wood lacquered doors, aluminum-wood doors, engineering doors, and custom interior doors — suitable for home clients, engineering clients, hotels/apartments, distributors, and design companies.",
    },
    {
      question: "Can engineering projects or hotels order custom bulk supply?",
      answer: "Yes. Provide project type, quantity, delivery city, target style, and budget. Chunhui will give initial recommendations based on product series, process configuration, and delivery milestones.",
    },
    {
      question: "What do distributors or design companies need to prepare?",
      answer: "Prepare your region, sales channels, target client types, and intended main products. Then discuss product catalogs, samples, supply cycles, and after-sales support.",
    },
  ],

  advantages: [
    { icon: "01", title: "Clear Product Range", desc: "Solid wood lacquered, aluminum-wood, engineering doors & custom interior doors covering home and engineering needs" },
    { icon: "02", title: "Stable Factory Delivery", desc: "Established processes for production, QC, scheduling, and bulk supply — ideal for hotel/apartment project support" },
    { icon: "03", title: "Channel Cooperation", desc: "Serving distributors, design companies, and designers with catalogs, samples, and stable long-term supply" },
    { icon: "04", title: "Convenient Consultation", desc: "Product, engineering, and distribution inquiries via phone, WeChat, or online form" },
  ],

  contact: {
    salesPhone: "0760-8820 3678",
    mobilePhone: "13809689692",
    afterSalePhone: "0760-8820 3678",
    workHours: "Mon–Sun  8:00 – 18:00",
    contactPerson: "Mr. Situ",
    wechatQR: "ziyuan/images/qrcode.png",
    secondaryWechatQR: "ziyuan/images/qrcode2.png",
    cta: "Get Product Information & Engineering Quotation",
    ctaSub: "After submitting your requirements, we will provide initial suggestions based on product series, space scenario, and quantity",
    intent: [
      { title: "Home Door Selection", desc: "For new homes, renovations, full-house customization. Focus on style, budget, eco-friendliness, and delivery time.", meta: "Solid Wood Lacquered / Aluminum-Wood / Custom" },
      { title: "Engineering Supply", desc: "For hotels, apartments, premium projects, bulk orders. Focus on quantity, lead time, specs, and stable supply.", meta: "Engineering Doors / Bulk Delivery" },
      { title: "Channel Partnership", desc: "For distributors, design companies, designer channels. Focus on product range, samples, catalogs, and long-term supply.", meta: "Distribution / Design / Sample Support" },
    ],
    detailLabels: ["Product & Engineering Inquiry", "Mobile", "Email 1", "Email 2", "WeChat", "Contact Person", "Service Hours"],
    response: [
      { num: "01", title: "Confirm Requirements", desc: "Confirm product type, client type, quantity, city, and delivery time." },
      { num: "02", title: "Initial Suggestions", desc: "Based on home, engineering, or distribution needs, recommend corresponding product series and configuration." },
      { num: "03", title: "Quotation Discussion", desc: "Discuss quotation based on dimensions, process, quantity, hardware, and logistics." },
      { num: "04", title: "Samples & Materials", desc: "For distribution or engineering cooperation, discuss catalogs, samples, and project materials." },
    ],
  },

  nav: [
    { label: "Home", href: "index.html" },
    { label: "Products", href: "product-center.html" },
    { label: "About Us", href: "guanyuwomen/index.html" },
    { label: "News & Cases", href: "xinwendongtai/index.html" },
    { label: "Contact", href: "lianxiwomen/index.html" },
  ],

  ui: {
    langBtn: "中文",
    scrollHint: "Products · Factory · Engineering Delivery",
    heroTitle: "Chunhui Doors",
    heroSub: "Solid wood lacquered & aluminum-wood door manufacturer for home décor, engineering, hotels & distribution",
    heroProof: ["Solid Wood Lacquered / Aluminum-Wood", "Bulk Engineering Supply", "Zhongshan Factory", "Custom Doors"],
    heroBtnPrimary: "Get Product Solutions",
    heroBtnSecondary: "View Product Lines",
    solutionsTitle: "Tailored Interior Door Solutions for Every Need",
    solutionsSub: "Whether home renovation, engineering supply, or channel partnership — we provide product recommendations based on your space, budget, quantity, and delivery needs.",
    productsEyebrow: "PRODUCTS",
    productsTitle: "Product Center",
    productsMore: "View Full Product Center",
    productEnquire: "Enquire Now",
    advantagesEyebrow: "WHY CHUNHUI",
    advantagesTitle: "Manufacturing Capability & Delivery Advantages",
    processEyebrow: "PROCESS",
    processTitle: "From Requirements to Stable Delivery",
    faqTitle: "Frequently Asked Questions",
    contactEyebrow: "CONTACT",
    contactTitle: "Contact Us",
    contactFormTitle: "Online Message · Get Product Solutions",
    contactFormNote: "Please visit the contact page to fill in product type, project quantity, city, and delivery time. Our sales team will respond promptly.",
    contactFormLink: "Go to Contact Page",
    aboutEyebrow: "ABOUT CHUNHUI",
    aboutClientsLabel: "Target Clients",
    newsReadMore: "Read More",
    newsConsult: "Inquire about related products",
    caseConsult: "Inquire about similar projects",
    backHome: "Back to Home",
    footerBrand: "Chunhui Doors",
    footerLogoMark: "CHUNHUI",
    footerLogoRest: " DOORS",
    footerNewsBrand: "Chunhui Doors News Center",
    copyright: "All rights reserved",
    formSubmitText: "Submit · Await Contact",
    formSubmitting: "Submitting, please wait...",
    formSuccess: "Inquiry sent. Our sales team will contact you soon.",
    formError: "Submission failed. Please try again or call 0760-8820 3678.",
  },
};
